# Generated by Django 5.1.2 on 2024-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpikipage',
            name='group_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpikipage',
            name='group_perms_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpikipage',
            name='other_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpikipage',
            name='other_perms_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpikipage',
            name='owner_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpikipage',
            name='owner_perms_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='group_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='group_perms_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='other_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='other_perms_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='owner_perms_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pikipage',
            name='owner_perms_write',
            field=models.BooleanField(default=True),
        ),
    ]
